spring:
  application:
    name: item-service
  #cloud:
    #config:
      #enabled: true
      #uri: http://localhost:8080
             
server:
  port: 8080
  
eureka:
  client:
    #fetch-registry: true
    #register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka

resilience4j.circuitbreaker:
    instances:
        productosCB:
            registerHealthIndicator: true
            slidingWindowSize: 10
            permittedNumberOfCallsInHalfOpenState: 3
            slidingWindowType: TIME_BASED
            minimumNumberOfCalls: 4
            waitDurationInOpenState: 5s
            failureRateThreshold: 50
            eventConsumerBufferSize: 10
        todosCB:
            registerHealthIndicator: true
            slidingWindowSize: 10
            permittedNumberOfCallsInHalfOpenState: 3
            slidingWindowType: TIME_BASED
            minimumNumberOfCalls: 4
            waitDurationInOpenState: 5s
            failureRateThreshold: 50
            eventConsumerBufferSize: 10